#!/usr/bin/env ruby

# require 'chef'

cookbook_path           = "#{ENV['HOME']}/Chef"
node_name               = "#{ENV['KNIFE_NODE_NAME']}"
client_key              = "#{ENV['KNIFE_CLIENT_KEY']}"
chef_server_url         = "#{ENV['KNIFE_CHEF_SERVER']}"
env='dev1'

zs_roles = Dir.entries(File.join(cookbook_path, 'zs-role/recipes')).map!{ |x| x.sub("\.rb","") }

rest = Chef::REST.new(chef_server_url, node_name, client_key)
request = { "run_list"  => [ "zs-role" ] }
cookbooks = rest.post("environments/#{env}/cookbook_versions", request)

cookbooks.each_key{ |k| 
  printf "%-20s %s\n", cookbooks[k].name, cookbooks[k].version
}

