#!/usr/bin/env ruby

require 'rubygems'
require 'chef'

node_name               = "#{ENV['KNIFE_NODE_NAME']}"
client_key              = "#{ENV['KNIFE_CLIENT_KEY']}"
chef_server_url         = "#{ENV['KNIFE_CHEF_SERVER']}"

rest = Chef::REST.new(chef_server_url, node_name, client_key)

env='dev1'

request = { "run_list"  => [ "zs-role" ] }
cookbooks = rest.post("environments/#{env}/cookbook_versions", request)

cookbooks.each_key{ |k| 
  printf "%-20s %s\n", cookbooks[k].name, cookbooks[k].version
 }

